### PR TITLE
Fixed formatting problem.

### PR DESCRIPTION
**Pull request by aborg0**

### CODE REVIEW

**Comment by galejwnaylor** [comment]
This looks like a good change to make, but I think the tick mark after "./"
should have been replaced with a back-tick, instead of adding the back-tick
after the tick-mark:

_**Should_\* set **rdf:about** to `""` (or `"./"'` if `xml:base` is not
set))*

Shouldn't the change be:

_**Should_\* set **rdf:about** to `""` (or `"./"` if `xml:base` is not set))*
    ?

Also, should we merge the pull request or make the change directly in
Markdown?

Gale

**Comment by aborg0** [comment]
@galejwnaylor You are absolutely right. I made a mistake there.

**Comment by galejwnaylor** [comment]
No problem. I'll find out the right procedure for making the change. Thanks.

**Comment by galejwnaylor** [comment]
As this was just a typo, I went ahead and made the changes. I also cleaned
up some spacing and other minor issues.

I wasn't sure if the double-braces in the last line were a typo or not, so
I left them in: "May parse the {/workflowBundle.rdf}} according to the XML
schema if the xsi:type="WorkflowBundleDocument" is set on the rdf:RDF
element."

Gale

**Pull request closed without merging**
